# Generated by Django 4.2.1 on 2023-05-06 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mmorpg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
