# Generated by Django 4.2.1 on 2023-05-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmorpg', '0002_remove_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='profile',
            name='discord',
            field=models.CharField(default='no discord', max_length=32, verbose_name='Discord'),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram',
            field=models.CharField(default='no telegram', max_length=32, verbose_name='Telegram'),
        ),
    ]
